name: Montra Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Run Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          # If you wish to fail your job when the Quality Gate is red, uncomment the
          # following lines. This would typically be used to fail a deployment.
          # - uses: sonarsource/sonarqube-quality-gate-action@master
          #   timeout-minutes: 5
          #   env:
          #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install Dependence & Test & Build
        run: |
          npm install yarn -g
          yarn
          yarn test
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
